apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoguard-deployment
  labels:
    app: demoguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoguard
  template:
    metadata:
      labels:
        app: demoguard
    spec:
      containers:
      - name: demoguard
        image: ddonahuex/demoguard:standard  # Image TAG: standard=CVEs, chainguard=0 CVEs
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
