apiVersion: v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multistage
  namespace: chainguard-demo
  labels:
    app: multistage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multistage
  template:
    metadata:
      labels:
        app: multistage
    spec:
      containers:
      - name: app
        image: localhost:5000/hello-melange-apko:multi-stage-latest   # or single-stage-latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: multistage-svc
  namespace: chainguard-demo
spec:
  type: NodePort
  selector:
    app: multistage
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080